
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Star } from "lucide-react";

const AIInsights = () => {
  // These would normally be generated by an AI based on the user's data
  const insights = [
    {
      id: 1,
      type: 'pattern',
      message: 'You tend to make the most progress on weekdays. Consider adding more structure to your weekend routine.',
    },
    {
      id: 2,
      type: 'motivation',
      message: 'You've consistently logged your meals for 14 days! This habit alone increases your chance of success by 60%.',
    },
    {
      id: 3,
      type: 'suggestion',
      message: 'Based on your recent meal logs, try increasing protein intake by 10-15g daily to support your muscle recovery.',
    }
  ];

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-lg flex items-center">
          <Star className="w-5 h-5 mr-2 text-amber-400" />
          AI Insights & Tips
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-3">
          {insights.map(insight => (
            <div 
              key={insight.id} 
              className="p-3 rounded-lg bg-gradient-to-r from-blue-50 to-purple-50 border border-blue-100"
            >
              <p className="text-sm">{insight.message}</p>
            </div>
          ))}
        </div>
        
        <p className="text-xs text-gray-500 mt-3">
          Insights are generated based on your progress data and updated weekly. The more data you provide, the more personalized your insights will be.
        </p>
      </CardContent>
    </Card>
  );
};

export default AIInsights;
