// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgmpbyqypyeoauipegwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnbXBieXF5cHllb2F1aXBlZ3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDE2NjksImV4cCI6MjA1OTc3NzY2OX0.alKueYUpHl-MCHf5gYEUHCQ9N0mIu5Np2wadFBZuX2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);